import pygame


#MEDIDAS DO JOGO
WIDTH = 750
HEIGHT = 700
pygame.display.set_caption('The Rise Of LequeLeto')

#CONSTANTES DE ALTURA E LARGURA
PLAYER_WIDTH = 45
PLAYER_HEIGHT = 40
BRICK_WIDTH=50
BRICK_HEIGHT=50
QUEBRAVEL_WIDTH=50
QUEBRAVEL_HEIGHT=50
BOMB_WIDTH=65
BOMB_HEIGHT=65
EXP_WIDTH=100
EXP_HEIGHT=100